export * from './components/list/list-patient.component'
export * from './components/create/create-patient.component'
export * from './components/chart/patient-chart.component'
export * from './components/chart/upcoming/upcoming-appointment.component'
export * from './components/chart/previous/previous-appointment.component'
export * from  './components/chart/patient.case/patient-chart-case.component'